---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tigris)
library(sf)
library(tidyverse)
```


```{r}
countries <- read.csv("countries.csv")

long <- countries %>%
  gather("year", val, -Country) %>%
  mutate(
    year = as.numeric(str_replace_all(year, "y", "20"))
  )

long %>%
  filter(year == 2021) %>%
  filter(val > 0) %>%
  pull(Country) %>%
  unique()
```

```{r}
long %>% filter(Country == "China")
```



```{r, fig.width=10}
ggplot(long %>% filter(Country != "China")) +
  geom_line(aes(x=year, y=val, color=Country)) +
  theme(legend.position="none")
```
```{r}
totals <- long %>%
  group_by(year) %>%
  summarise(total = sum(val)) 

totals

# total outside of US:
#2010-11 : 847 --- from bap site
#2020-21 : 3969

countries %>%
  arrange(desc(y21))

3969-847

ggplot(totals) +
  geom_line(aes(x=year, y=total))

totals %>%
  left_join(
    long %>% filter(Country == "China")
  ) %>%
  mutate(pctChina = val / total)
```

```{r}
cs <- data.frame(
  year=c(2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021),
  us=c(23358, 22728, 22584, 22516, 22818, 22932, 23392, 23773, 24395, 24155, 24525),
  other=c(847, 959, 1255, 1473, 1820, 2159, 2566, 2970, 3528, 4143, 3969)
)

cs %>%
  mutate(pctF = other / (us + other))

24155-23358
4143-847

mean(cs$us)

ggplot(cs) +
  geom_line(aes(x=year, y=us)) +
  scale_y_continuous(lim=c(0, 25000))

ggplot(cs) + 
  geom_line(aes(x=year, y=other))  +
  scale_y_continuous(lim=c(0, 5000))
```

